package com.veritransit.inspector.ai

/**
 * Fixed espeak-ng (en-us) phoneme strings for every alert sentence.
 * Generated from espeak-ng 1.52 output — do not hand-edit; regenerate with
 * T/opencode/kokoro_phrases.txt if VoiceAlertText wording changes.
 */
object KokoroPhrases {
    val SENTENCE: Map<String, String> = mapOf(
        "Verified." to "vˈɛɹᵻfˌaɪd",
        "Suspect package." to "sˈʌspɛkt pˈækɪdʒ",
        "Rejected." to "ɹᵻdʒˈɛktᵻd",
        "Held for review." to "hˈɛld fɔːɹ ɹᵻvjˈuː",
        "Do not load this carton." to "duːnˌɑːt lˈoʊd ðɪs kˈɑːɹtən",
        "Inspection attention." to "ɪnspˈɛkʃən ɐtˈɛnʃən",
        "Hold for review." to "hˈoʊld fɔːɹ ɹᵻvjˈuː",
        "E-Way Bill." to "ˈiːwˈeɪ bˈɪl",
        "line discrepant." to "lˈaɪn dɪskɹˈɛpənt",
        "lines discrepant." to "lˈaɪnz dɪskɹˈɛpənt",
        "unlisted parcel observed." to "ʌnlˈɪstᵻd pˈɑːɹsəl əbzˈɜːvd",
        "unlisted parcels observed." to "ʌnlˈɪstᵻd pˈɑːɹsəlz əbzˈɜːvd",
        "Label signature does not verify. Not issued by this platform." to "lˈeɪbəl sˈɪɡnɪtʃɚ dʌznˌɑːt vˈɛɹᵻfˌaɪ nˌɑːt ˈɪʃuːd baɪ ðɪs plˈætfɔːɹm",
        "Label belongs to a different shipment." to "lˈeɪbəl bᵻlˈɔŋz tʊ ɐ dˈɪfɹənt ʃˈɪpmənt",
        "QR and barcode disagree. Label may have been moved." to "kjˌuːˈɑːɹ ænd bˈɑːɹkoʊd dˌɪsɐɡɹˈiː lˈeɪbəl mˌeɪhɐv bˌɪn mˈuːvd",
        "This package code was already scanned." to "ðɪs pˈækɪdʒ kˈoʊd wʌz ɔːlɹˌɛdi skˈænd",
        "An older copy of a reprinted label." to "ɐn ˈoʊldɚ kˈɑːpi əvɚ ɹᵻpɹˈɪntᵻd lˈeɪbəl",
        "Photo shows tampering." to "fˈoʊɾoʊ ʃˈoʊz tˈæmpɚɹɪŋ",
        "Package is not on this shipment's list." to "pˈækɪdʒ ɪz nˌɑːt ˌɔn ðɪs ʃˈɪpmənts lˈɪst",
        "Master declares more inner boxes than were found." to "mˈæstɚ dᵻklˈɛɹz mˈɔːɹ ˈɪnɚ bˈɑːksᵻz ðɐn wɜː fˈaʊnd",
        "Inner box belongs to a different master." to "ˈɪnɚ bˈɑːks bᵻlˈɔŋz tʊ ɐ dˈɪfɹənt mˈæstɚ",
        "Extra box found inside a sealed master." to "ˈɛkstɹə bˈɑːks fˈaʊnd ɪnsˈaɪd ɐ sˈiːld mˈæstɚ",
        "Contents do not match the declaration." to "kˈɑːntɛnts duːnˌɑːt mˈætʃ ðə dˌɛklɚɹˈeɪʃən",
        "one" to "wˈʌn",
        "two" to "tˈuː",
        "three" to "θɹˈiː",
        "four" to "fˈɔːɹ",
        "five" to "fˈaɪv",
        "six" to "sˈɪks",
        "seven" to "sˈɛvən",
        "eight" to "ˈeɪt",
        "nine" to "nˈaɪn",
        "ten" to "tˈɛn",
        "zero" to "zˈiəɹoʊ",
        "eleven" to "ᵻlˈɛvən",
        "twelve" to "twˈɛlv",
        "thirteen" to "θˈɜːtiːn",
        "fourteen" to "fˈɔːɹtiːn",
        "fifteen" to "fˈɪftiːn",
        "sixteen" to "sˈɪkstiːn",
        "seventeen" to "sˈɛvəntˌiːn",
        "eighteen" to "ˈeɪtiːn",
        "nineteen" to "nˈaɪntiːn",
        "twenty" to "twˈɛnti",
        "thirty" to "θˈɜːɾi",
        "forty" to "fˈɔːɹɾi",
        "fifty" to "fˈɪfti",
        "sixty" to "sˈɪksti",
        "seventy" to "sˈɛvənti",
        "eighty" to "ˈeɪɾi",
        "ninety" to "nˈaɪnti",
    )

    /** Spoken letter names (codes are spelled out, never read as words). */
    val LETTER: Map<Char, String> = mapOf(
        'A' to "eɪ",
        'B' to "biː",
        'C' to "siː",
        'D' to "diː",
        'E' to "iː",
        'F' to "ɛf",
        'G' to "dʒiː",
        'H' to "eɪtʃ",
        'I' to "aɪ",
        'J' to "dʒeɪ",
        'K' to "keɪ",
        'L' to "ɛl",
        'M' to "ɛm",
        'N' to "ɛn",
        'O' to "oʊ",
        'P' to "piː",
        'Q' to "kjuː",
        'R' to "ɑːɹ",
        'S' to "ɛs",
        'T' to "tiː",
        'U' to "juː",
        'V' to "viː",
        'W' to "dʌbəljuː",
        'X' to "ɛks",
        'Y' to "waɪ",
        'Z' to "ziː",
    )

    /** Digit words, resolved through SENTENCE above. */
    val DIGIT_WORD: Map<Char, String> = mapOf(
        '0' to "zero",
        '1' to "one",
        '2' to "two",
        '3' to "three",
        '4' to "four",
        '5' to "five",
        '6' to "six",
        '7' to "seven",
        '8' to "eight",
        '9' to "nine",
    )
}
