#!/usr/bin/env bash
# =============================================================================
# VeriTransit — build the database from nothing.
#
#   ./db/scripts/setup.sh              rebuild schema + demo data (destructive)
#   ./db/scripts/setup.sh --schema     schema only, no demo data
#   ./db/scripts/setup.sh --keep-creds reuse the passwords already in db/.env
#
# Safe to re-run: it drops and recreates the `veritransit` database each time.
# Nothing outside that database is touched.
# =============================================================================
set -euo pipefail

DB_NAME=veritransit
DB_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$DB_ROOT/.env"
VENV="$DB_ROOT/.venv"
SEED_ONLY=0
SCHEMA_ONLY=0
KEEP_CREDS=0

for arg in "$@"; do
  case "$arg" in
    --schema)      SCHEMA_ONLY=1 ;;
    --seed)        SEED_ONLY=1 ;;
    --keep-creds)  KEEP_CREDS=1 ;;
    *) echo "unknown option: $arg" >&2; exit 2 ;;
  esac
done

command -v psql >/dev/null || { echo "psql not found — brew install postgresql@18" >&2; exit 1; }
pg_isready -q || { echo "postgres is not running — brew services start postgresql@18" >&2; exit 1; }

# --- credentials -------------------------------------------------------------
if [[ $KEEP_CREDS -eq 1 && -f "$ENV_FILE" ]]; then
  # shellcheck disable=SC1090
  source "$ENV_FILE"
  APP_PW="$VT_APP_PASSWORD"; RO_PW="$VT_RO_PASSWORD"
else
  APP_PW=$(LC_ALL=C tr -dc 'A-Za-z0-9' </dev/urandom | head -c 28)
  RO_PW=$(LC_ALL=C tr -dc 'A-Za-z0-9' </dev/urandom | head -c 28)
fi

LAN_IP=$(ipconfig getifaddr "$(route -n get default 2>/dev/null | awk '/interface:/{print $2}')" 2>/dev/null || echo 127.0.0.1)

# --- database + roles --------------------------------------------------------
if [[ $SEED_ONLY -eq 0 ]]; then
  echo "▸ creating database and roles"
  psql -d postgres -v ON_ERROR_STOP=1 -q <<SQL
DROP DATABASE IF EXISTS ${DB_NAME};
DO \$\$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='veritransit_app') THEN
    CREATE ROLE veritransit_app LOGIN;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='veritransit_ro') THEN
    CREATE ROLE veritransit_ro LOGIN;
  END IF;
END \$\$;
ALTER ROLE veritransit_app PASSWORD '${APP_PW}';
ALTER ROLE veritransit_ro  PASSWORD '${RO_PW}';
CREATE DATABASE ${DB_NAME} ENCODING 'UTF8';
SQL
  psql -d "$DB_NAME" -v ON_ERROR_STOP=1 -q -c \
    "REVOKE ALL ON SCHEMA public FROM PUBLIC; GRANT USAGE ON SCHEMA public TO veritransit_app, veritransit_ro;"

  echo "▸ applying migrations"
  for f in "$DB_ROOT"/migrations/V*.sql; do
    printf '   %s\n' "$(basename "$f")"
    psql -d "$DB_NAME" -v ON_ERROR_STOP=1 -q -f "$f"
  done
fi

# --- demo data ---------------------------------------------------------------
if [[ $SCHEMA_ONLY -eq 0 ]]; then
  if [[ ! -x "$VENV/bin/python" ]]; then
    echo "▸ creating python venv for label signing"
    python3 -m venv "$VENV"
    "$VENV/bin/pip" install -q --disable-pip-version-check cryptography
  fi
  echo "▸ generating demo data (real Ed25519 label signatures)"
  "$VENV/bin/python" "$DB_ROOT/scripts/generate_seed.py"
  echo "▸ loading demo data"
  psql -d "$DB_NAME" -v ON_ERROR_STOP=1 -q -f "$DB_ROOT/seed/S1__demo_data.sql" >/dev/null
  echo "▸ verifying label signatures"
  "$VENV/bin/python" "$DB_ROOT/scripts/verify_labels.py" "$DB_NAME"
fi

# --- credentials file --------------------------------------------------------
umask 077
cat > "$ENV_FILE" <<ENV
# VeriTransit database credentials — generated by db/scripts/setup.sh
# NOT in version control. Regenerate with: ./db/scripts/setup.sh
VT_DB_HOST="${LAN_IP}"
VT_DB_PORT="5432"
VT_DB_NAME="${DB_NAME}"

VT_APP_USER="veritransit_app"
VT_APP_PASSWORD="${APP_PW}"
VT_APP_URL="postgresql://veritransit_app:${APP_PW}@${LAN_IP}:5432/${DB_NAME}"
VT_APP_JDBC="jdbc:postgresql://${LAN_IP}:5432/${DB_NAME}?user=veritransit_app&password=${APP_PW}"

VT_RO_USER="veritransit_ro"
VT_RO_PASSWORD="${RO_PW}"
VT_RO_URL="postgresql://veritransit_ro:${RO_PW}@${LAN_IP}:5432/${DB_NAME}"

# §4.2 label signing key. Public half is also in the signing_keys table.
VT_SIGNING_KEY_ID="vt-key-2026-01"
VT_SIGNING_KEY_PRIVATE="${DB_ROOT}/keys/signing_key.pem"
VT_SIGNING_KEY_PUBLIC="$(cat "$DB_ROOT/keys/signing_key.pub" 2>/dev/null || echo '')"
ENV

echo
echo "✓ ${DB_NAME} ready on ${LAN_IP}:5432"
echo "  credentials: db/.env"
